// Generated by CoffeeScript 1.12.4
var assertType, bindArgs, bindFunc, bindMethod, bindToString, isDev, shiftArray;

assertType = require("assertType");

isDev = require("isDev");

shiftArray = Function.prototype.call.bind(Array.prototype.shift);

bindArgs = function() {
  var args, func, offset;
  args = arguments;
  func = shiftArray(args);
  assertType(func, Function);
  offset = args.length;
  return bindToString(func, function() {
    var arg, i, index, len;
    for (index = i = 0, len = arguments.length; i < len; index = ++i) {
      arg = arguments[index];
      args[offset + index] = arg;
    }
    return func.apply(this, args);
  });
};

bindFunc = function(func, context, args) {
  assertType(func, Function);
  return bindToString(func, function() {
    return func.apply(context, args || arguments);
  });
};

bindMethod = function(obj, key, args) {
  var method;
  assertType(key, String);
  method = obj[key];
  assertType(method, Function);
  return bindToString(method, function() {
    return method.apply(obj, args || arguments);
  });
};

bindToString = isDev ? function(orig, func) {
  return Object.defineProperty(func, "toString", {
    value: function() {
      return orig.toString();
    }
  });
} : function(orig, func) {
  return func;
};

module.exports = {
  args: bindArgs,
  func: bindFunc,
  method: bindMethod,
  toString: bindToString
};
